name: Check the builds aren't broken
on: push

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  wasm:
    name: "Build wasm"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker run -it -v $(pwd):/src -u $(id -u):$(id -g) emscripten/emsdk make -j8 DEBUG=1 wasm
  native:
    name: "Build native"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker run -it -v $(pwd):/src debian sh -c "apt update && apt -yy install gcc make libsdl2-dev libz-dev && make -C /src -j8 DEBUG=1 native"
